@startuml record
left to right direction
skinparam BackgroundColor transparent
skinparam componentStyle rectangle

title record.py block diagram
component "config" as config #aqua
component "Real Image" as in #red
component "time" as t #lime
component "dt" as dt #lime
component "cx" as cx #lime
component "cy" as cy #lime
component "width" as width #lime
component "height" as height #lime

component "record.py" as record {
    component "init" as init
    component "start" as start {
        interface "Function Call" as call
        component "Camera" as camera {
            portin "real" as preal
            portout "frame" as pframe
        }

        component "time_manager" as cm { 
            portout "curr_time" as ptime
            portout "dt" as pdt
            portin " " as pin1
        }

        component "detector" as detector { 
            portin "frame" as detframe
            portout "cx" as pcx
            portout "cy" as pcy
            portout "width" as pwidth
            portout "height" as pheight
        }
        call --> pin1
    } 

    init -u[hidden]- camera
    detector -u[hidden]- cm

    pframe --> detframe
}
in --> preal
config -l-> init
pcx --> cx
pcy --> cy
pwidth --> width
pheight --> height
ptime ---> t
pdt ---> dt


@enduml