@startuml camera
left to right direction
skinparam BackgroundColor transparent
skinparam componentStyle rectangle
skinparam linetype ortho

title camera.py block diagram
component "Real Image" as in #red
component "Frame" as out  #lime
component "config" as config #aqua

component "Camera.py" as camera {
    component "init" as init
    component "initRecording" as initRec
    component "startRecording" as read {
        component "processFrame" as proc #Orange {
            portin "real" as p1
            portout "frame" as p2
        }
    }

    config -l-> init
    init -u[hidden]- read

}
in --> p1
p2 --> out
@enduml