@startuml detector
left to right direction
skinparam BackgroundColor transparent
skinparam componentStyle rectangle

title detector.py block diagram
component "config" as config #aqua
component "frame" as f #red
component "cx" as cx #lime
component "cy" as cy #lime
component "width" as width #lime
component "height" as height #lime

component "detector.py" as detector { 
    component init {
        
    }
    init -[hidden]-- reading
    component "reading" as reading {
        portin "frame" as p0
        portout "cx" as p1
        portout "cy" as p2
        portout "width" as p3
        portout "height" as p4
    }
    
}
config -l--> init
f ---> p0

p1 --> cx
p2 --> cy
p3 --> width
p4 --> height

@enduml