@startuml detector
left to right direction
skinparam BackgroundColor transparent
skinparam componentStyle rectangle
skinparam linetype ortho

title detector.py block diagram
component "config" as config #aqua
component "frame" as f #red
component "objects" as obj #lime

component "detector.py" as detector { 
    component init
    component "measurement" as measurement {
        portin "frame" as p0
        portout "objects" as p1
        component "findClosestCentroid" as close
        component "removeOldObjects" as oldobj
        component "incrementObjectAge" as incobj
    }

    init -u[hidden]- measurement
    p0 --> close
    close --> incobj
    incobj --> oldobj
    oldobj -d--> p1
}

config -l-> init
f --> p0
p1 --> obj

@enduml