@startuml time_manager

left to right direction
skinparam BackgroundColor transparent
skinparam componentStyle rectangle
skinparam linetype ortho

title time_manager.py block diagram

component "curr_time" as ctime #lime
component " " as in1 #red
component " " as in #Aqua

component "time_manager.py" as cm {
    component init 
    component sync {
        portout "curr_time" as pin0
        portin " " as pin1
    }
    init -u[hidden]-> sync
    
}

in -l-> init
in1 --> pin1 : function call
pin0 ---> ctime

@enduml